inherit_from:
  - ~/.rubocop.yml

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false